In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('gym_gridworld:gridworld-v4', size=3) 

In [6]:
obs, reward, done, info = env.step(1)

In [51]:
UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3

def fvmcPrediction(policy=[0.25,0.25,0.25,0.25], gamma=1):
    V = [0 for i in env.observation_space]
    returns = [[] for i in env.observation_space]
    
    for i in range(10000):
        
        episode = {'S':[env.reset()], 'A':[], 'R':[], 'T':0}
        done = False
        while not done:
            action = np.random.choice([UP, RIGHT, DOWN, LEFT], p=policy)
            obs, reward, done, info = env.step(action)
            episode['A'].append(action)
            episode['R'].append(reward)
            if not done:
                episode['S'].append(obs)
            episode['T'] += 1
        
        G = 0
        for t in reversed(range(episode['T'])):
            G = gamma * G + episode['R'][t]
            if episode['S'][t] not in episode['S'][0:t]:
                St_index = env.observation_space.index(episode['S'][t])
                returns[St_index].append(G)
                V[St_index] = np.mean(returns[St_index])
        
    return V, returns
    
            
        

In [43]:
a, b = fvmcPrediction()
np.array(a).reshape(3,3)

In [48]:
np.array(a).reshape(3,3)

array([[-26.07      , -23.1954023 , -19.14492754],
       [-23.91463415, -22.15384615, -15.57142857],
       [-20.        , -12.27536232,   0.        ]])

In [50]:
a, b = fvmcPrediction()
np.array(a).reshape(3,3)

array([[-24.82      , -22.36746988, -19.96503497],
       [-22.72871046, -18.97450753, -13.65739385],
       [-21.2974359 , -14.12784091,   0.        ]])

In [52]:
a, b = fvmcPrediction()
np.array(a).reshape(3,3)

array([[-25.8309    , -23.7291441 , -21.43484065],
       [-23.93294602, -20.36404022, -14.81122521],
       [-21.30576859, -14.93313584,   0.        ]])

In [53]:
a, b = fvmcPrediction()
np.array(a).reshape(3,3)

array([[-25.9679    , -23.99589719, -21.55697887],
       [-23.96081277, -20.35817781, -14.77106742],
       [-21.44542871, -15.07234523,   0.        ]])

In [54]:
a, b = fvmcPrediction()
np.array(a).reshape(3,3)

array([[-25.8249    , -23.86453411, -21.54215457],
       [-23.93965099, -20.42170362, -15.03956886],
       [-21.35428096, -14.95293786,   0.        ]])

In [55]:
a, b = fvmcPrediction()
np.array(a).reshape(3,3)

array([[-26.384     , -24.44328161, -22.00857378],
       [-24.28521593, -20.8537411 , -15.21673699],
       [-21.75518263, -15.3309189 ,   0.        ]])