In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('gym_gridworld:gridworld-v4', size=3, player_pos=[0,0], goal_pos=[[2,2]]) 

In [3]:
UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3

In [4]:
def fvmcPrediction(policy=[0.25,0.25,0.25,0.25], gamma=1):
    #V = [0 for i in env.observation_space]
    returns = [[] for i in env.observation_space]
    
    for i in range(10000):
        
        episode = {'S':[env.reset()], 'A':[], 'R':[], 'T':0}
        done = False
        while not done:
            action = np.random.choice([UP, RIGHT, DOWN, LEFT], p=policy)
            obs, reward, done, info = env.step(action)
            episode['A'].append(action)
            episode['R'].append(reward)
            if not done:
                episode['S'].append(obs)
            episode['T'] += 1
        
        G = 0
        for t in reversed(range(episode['T'])):
            G = gamma * G + episode['R'][t]
            if episode['S'][t] not in episode['S'][0:t]:
                St_index = env.observation_space.index(episode['S'][t])
                returns[St_index].append(G)
                #V[St_index] = np.mean(returns[St_index])
    V = [np.mean(i) if len(i) > 0 else 0 for i in returns ]
        
    return V, returns     

In [5]:
a, b = fvmcPrediction()
np.array(a).reshape(3,3)

array([[-25.9309    , -23.79124579, -21.48336106],
       [-23.98277326, -20.54890922, -14.83823946],
       [-21.52327902, -14.93821575,   0.        ]])

In [32]:
a, b = fvmcPrediction()
np.array(a).reshape(3,3)

array([[-26.096     , -24.29891371, -22.01630252],
       [-24.1854585 , -20.69092185, -15.40180879],
       [-21.66318754, -15.35466516,   0.        ]])

In [8]:
env = gym.make('gym_gridworld:gridworld-v4', size=4, player_pos=[0,3], goal_pos=[[3,3], [0,0]]) 

In [13]:
a, b = fvmcPrediction()
np.array(a).reshape(4,4)

array([[  0.        , -12.94262725, -18.94979647, -20.97025   ],
       [-12.95195673, -16.96533663, -18.99294383, -19.0237013 ],
       [-18.95212665, -19.02053048, -17.04274316, -13.03391636],
       [-21.23328999, -19.17568598, -13.00126783,   0.        ]])

In [ ]:
def epsilonSoftOnPolicyFvmcControl(epsilon):
    policy=[np.random.choice([UP, RIGHT, DOWN, LEFT]) for s in env.observation_space]
    Q = [{a: [0 for s in env.observation_space]} for a in [UP, RIGHT, DOWN, LEFT]]
    returns = [{a: [[] for s in env.observation_space]} for a in [UP, RIGHT, DOWN, LEFT]]
    
    for i in range(10000):
        
        episode = {'S':[env.reset()], 'A':[], 'R':[], 'T':0}
        done = False
        while not done:
            action = np.random.choice([UP, RIGHT, DOWN, LEFT], p=policy)
            obs, reward, done, info = env.step(action)
            episode['A'].append(action)
            episode['R'].append(reward)
            if not done:
                episode['S'].append(obs)
            episode['T'] += 1
        
        G = 0
        for t in reversed(range(episode['T'])):
            G = gamma * G + episode['R'][t]
            if episode['S'][t] not in episode['S'][0:t]:
                St_index = env.observation_space.index(episode['S'][t])
                returns[St_index].append(G)
                V[St_index] = np.mean(returns[St_index])
        
    return V, returns 

In [4]:
[{a: [0 for s in env.observation_space]} for a in [UP, RIGHT, DOWN, LEFT]]

[{0: [0, 0, 0, 0, 0, 0, 0, 0, 0]},
 {1: [0, 0, 0, 0, 0, 0, 0, 0, 0]},
 {2: [0, 0, 0, 0, 0, 0, 0, 0, 0]},
 {3: [0, 0, 0, 0, 0, 0, 0, 0, 0]}]