In [50]:
import numpy as np

In [72]:
a = np.identity(3*3).tolist()
for i in a:
    print(i)

[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]


In [56]:
np.reshape(a[0], (3,3))

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
grid = np.arange(9).reshape(3,3)
it = np.nditer(grid, flags=['multi_index'])

In [48]:
while not it.finished:
    print("%d <%s>" % (it[0], it.multi_index))
    it.iternext()

0 <(0, 0)>
1 <(0, 1)>
2 <(0, 2)>
3 <(1, 0)>
4 <(1, 1)>
5 <(1, 2)>
6 <(2, 0)>
7 <(2, 1)>
8 <(2, 2)>


In [35]:
a = np.arange(6).reshape(2,3)
it = np.nditer(a, flags=['multi_index'])
while not it.finished:
    print("%d <%s>" % (it[0], it.multi_index))
    it.iternext()

0 <(0, 0)>
1 <(0, 1)>
2 <(0, 2)>
3 <(1, 0)>
4 <(1, 1)>
5 <(1, 2)>


In [38]:
it = np.nditer(a, flags=['multi_index'])

In [41]:
?it

In [42]:
P = {}

In [44]:
P[1] = {a : [] for a in range(4)}

In [46]:
P

{1: {0: [], 1: [], 2: [], 3: []}}

In [71]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
it = np.nditer(a, flags=['multi_index'])
while not it.finished:
    print("%d <%s>" % (it[0], it.multi_index))
s    it.iternext()

TypeError: %d format: a number is required, not tuple

In [154]:
size = 3
UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3

sqr_size = size * size

observation_space = np.identity(sqr_size).tolist()

tr = {}

iterator = np.arange(sqr_size).reshape(size,size)
iterator = np.nditer(iterator, flags=['multi_index'])
while not iterator.finished:
    index = iterator.iterindex
    row, col = iterator.multi_index
    
    tr[index] = {a: observation_space[index] for a in range(4)}
    
    if row > 0:
        tr[index][UP] = observation_space[index - size]
    if row < size - 1:
        tr[index][DOWN] = observation_space[index + size]
    if col > 0:
        tr[index][LEFT] = observation_space[index - 1]
    if col < size - 1:
        tr[index][RIGHT] = observation_space[index + 1]
    
    iterator.iternext()

0 0 0
1 0 1
2 0 2
3 1 0
4 1 1
5 1 2
6 2 0
7 2 1
8 2 2


In [130]:
np.zeros((size, size))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [155]:
tr

{0: {0: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  1: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  2: [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  3: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]},
 1: {0: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  1: [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  2: [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
  3: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]},
 2: {0: [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  1: [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  2: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  3: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]},
 3: {0: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  1: [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
  2: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
  3: [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]},
 4: {0: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  1: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  2: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,

In [136]:
isOverflow = lambda x: x < 0 or x >= 4

In [140]:
isOverflow(3)

False

In [146]:
a = np.zeros(9)

In [147]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [151]:
observation_space

[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]

In [156]:
a = [1,1,1]

In [157]:
a == [1,1,1]

True

In [1]:
import gym

In [2]:
env = gym.make('gym_gridworld:gridworld-v2', size=3) 

In [23]:
env.render()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


In [13]:
env.step(0)

([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1, False, {})

In [21]:
env.step(1)

([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], 0, True, {})

In [22]:
env.step(2)

([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], 0, True, {})

In [16]:
env.step(3)

([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], -1, False, {})